version: 38
jobs:
- name: Deploy to Backup Machine
  steps:
  - !SSHCommandStep
    name: Deploy
    remoteMachine: 172.190.20.196
    userName: roymanclee
    privateKeySecret: private key
    commands: |
      sudo cp -r /home/roymanclee/hongzhengli.com/* /opt/1panel/apps/openresty/openresty/www/sites/hongzhengli.com/index/
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger {}
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
